FROM nginx:alpine

COPY index.html /usr/share/nginx/html
COPY geolocation.html /usr/share/nginx/html
COPY css/. /usr/share/nginx/html
COPY js/. /usr/share/nginx/html
COPY img/. /usr/share/nginx/html
COPY font-awesome/css/. /usr/share/nginx/html
COPY font-awesome/fonts/. /usr/share/nginx/html
COPY font-awesome/less/. /usr/share/nginx/html
COPY font-awesome/scss/. /usr/share/nginx/html
COPY fonts/. /usr/share/nginx/html